session:
  targets:
    - exe:tricorder
    - exe:tricorder-daemon
    - lib:atelier-core
    - lib:atelier-db
    - lib:atelier-testing
    - lib:tricorder-internal
    - test:atelier-test
    - test:tricorder-test
observability:
  log_file: /tmp/tricorder.log
  metrics:
    enabled: true
    port: 9091
  tracing:
    enabled: true
    service_name: tricorder
    otlp_endpoint: "http://localhost:4318"
