session:
observability:
  log_file: /tmp/tricorder.log
  metrics:
    enabled: true
    port: 9192
  tracing:
    enabled: true
    service_name: tricorder-legacy
    otlp_endpoint: "http://localhost:4318"
  observe:
    enabled: true
    service_name: tricorder-observe
    otlp_endpoint: "http://localhost:4318"
