name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ghc-versions:
    name: Get GHC versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.compute.outputs.ghc-versions }}
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Compute GHC versions
        id: compute
        shell: bash
        run: |
          versions=$(
            nix eval --json --file nix/package/common.nix \
              | jq -c '."ghc-versions" | [.[] | "ghc" + gsub("\\."; "")]'
          )
          echo "ghc-versions=$versions" >> "$GITHUB_OUTPUT"

  check:
    needs: ghc-versions
    name: Check ${{ matrix.system }}/${{ matrix.ghc-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-14
          - ubuntu-latest
        ghc-version: ${{ fromJson(needs.ghc-versions.outputs.versions) }}
        include:
          - os: macos-14
            system: aarch64-darwin
          - os: ubuntu-latest
            system: x86_64-linux
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            allow-unfree = true
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: tweag-tricorder
          authToken: "${{ secrets.CACHIX_TWEAG_TRICORDER_AUTH_TOKEN }}"
      - run: nix build '.#legacyChecks.${{ matrix.system }}.${{ matrix.ghc-version }}.all' -L

  results:
    name: Results
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check
    steps:
      - run: |
          result="${{ needs.check.result }}"
          if [[ "$result" != "success" ]]; then
            exit 1
          fi
