name: Release Hackage packages
on:
  push:
    branches: [main]
    paths:
      - "**/*.cabal"
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/ci.yml

  release-hackage-atelier-core:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
    with:
      package-name: atelier-core

  release-hackage-atelier-prelude:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - release-hackage-atelier-core
      - checks
    if: ${{ !failure() && needs.checks.result == 'success' }}
    with:
      package-name: atelier-prelude

  release-hackage-atelier-monitoring:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - release-hackage-atelier-core
      - release-hackage-atelier-prelude
      - checks
    if: ${{ !failure() && needs.checks.result == 'success' }}
    with:
      package-name: atelier-monitoring

  release-hackage-atelier-db:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
      - release-hackage-atelier-core
      - release-hackage-atelier-prelude
      - release-hackage-atelier-monitoring
    if: ${{ !failure() && needs.checks.result == 'success' }}
    with:
      package-name: atelier-db

  release-hackage-atelier-testing:
    needs:
      - checks
      - release-hackage-atelier-core
      - release-hackage-atelier-prelude
      - release-hackage-atelier-db
    if: ${{ !failure() && needs.checks.result == 'success' }}
    uses: ./.github/workflows/release-hackage-package.yml
    with:
      package-name: atelier-testing

  release-hackage-tricorder:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
      - release-hackage-atelier-core
      - release-hackage-atelier-prelude
    if: ${{ !failure() && needs.checks.result == 'success' }}
    with:
      package-name: tricorder

  release-hackage-tricorder-mcp:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
      - release-hackage-tricorder
    if: ${{ !failure() && needs.checks.result == 'success' }}
    with:
      package-name: tricorder-mcp
