name: Release
on:
  push:
    branches: [main]
    paths:
      - "**/*.cabal"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  checks:
    uses: ./.github/workflows/ci.yml

  release-hackage:
    needs: [checks]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - atelier-db
          - atelier-prelude
          - atelier-testing
          - atelier-core
          - tricorder
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: tweag-tricorder
          authToken: "${{ secrets.CACHIX_TWEAG_TRICORDER_AUTH_TOKEN }}"
      - uses: sol/haskell-autotag@a535f2ac35a62c541de1919b04984b2970866f71
        id: tagging
        with:
          package-path: ${{ matrix.package }}
          prefix: ${{ matrix.package }}-v
      - name: Pack
        run: nix build .#${{ matrix.package }}-sdist
      - name: Publish to Hackage
        uses: haskell-actions/hackage-publish@73c1489054aa60b7aa082cdde9b51502d960c0e1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: ${{ runner.temp }}/result/
          publish: false

  tricorder-tag:
    name: Tag new Tricorder version
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.tagging.outputs.created }}
      name: ${{ steps.tagging.outputs.name }}
      version: ${{ steps.tagging.outputs.version }}
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - uses: sol/haskell-autotag@a535f2ac35a62c541de1919b04984b2970866f71
        id: tagging
        with:
          package-path: tricorder

  build-binaries:
    name: Build binaries
    needs:
      - checks
      - tricorder-tag
    if: ${{ needs.tricorder-tag.outputs.created }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-darwin
        include:
          - system: x86_64-linux
            runs-on: ubuntu-latest
          - system: aarch64-darwin
            runs-on: macos-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: tweag-tricorder
          authToken: "${{ secrets.CACHIX_TWEAG_TRICORDER_AUTH_TOKEN }}"
      - name: Build
        run: nix build .#tricorder
      - name: Compress
        run: |
          compressed_name="tricorder_${{ matrix.system }}"
          cat result/bin/tricorder | gzip > "$compressed_name.gz"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: tricorder_${{ matrix.system }}
          path: tricorder_${{ matrix.system }}.gz

  publish-github:
    name: Publish binaries to GitHub
    needs:
      - build-binaries
      - tricorder-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: Extract from CHANGELOG
        run: |
          nix run .#get-changelog-section -- \
            ${{ needs.tricorder-tag.outputs.version }} \
            tricorder/CHANGELOG.md \
          | tee release-notes.md
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: binaries
          merge-multiple: true
      - name: Publish to GitHub
        run: |
          gh release create \
            '${{ needs.tricorder-tag.outputs.name }}' \
            --title 'Tricorder ${{ needs.tricorder-tag.outputs.name }}' \
            --notes-file release-notes.md \
            --verify-tag \
            binaries/*
