name: Create draft Tricorder GitHub release
on:
  push:
    tags:
      - "tricorder-*"
  workflow_dispatch:
    inputs:
      ref:
        description: Tag or ref to release
        required: false
        type: string
        default: ""
jobs:
  meta:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
      tag: ${{ steps.meta.outputs.tag }}
      package: ${{ steps.meta.outputs.package }}
    steps:
      - id: meta
        run: |
          tag="$(echo '${{ case(inputs.ref != '', inputs.ref, github.ref) }}' | sed 's!refs/tags/!!')"
          version="$(echo "$tag" | sed -E 's/^tricorder-(.+-)?//')"
          package="$(echo "$tag" | sed -E 's/-[^-]+$//')"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "package=$package" >> $GITHUB_OUTPUT

  build-binaries:
    name: Build binaries
    needs:
      - meta
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-darwin
        include:
          - system: x86_64-linux
            runs-on: ubuntu-latest
          - system: aarch64-darwin
            runs-on: macos-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          ref: ${{ needs.meta.outputs.tag }}
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: tweag-tricorder
          authToken: "${{ secrets.CACHIX_TWEAG_TRICORDER_AUTH_TOKEN }}"
      - name: Build
        run: nix build '.#${{ needs.meta.outputs.package }}'
      - name: Compress
        run: |
          compressed_name="${{ needs.meta.outputs.package }}_${{ matrix.system }}"
          cat 'result/bin/${{ needs.meta.outputs.package }}' | gzip > "$compressed_name.gz"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ needs.meta.outputs.package }}_${{ matrix.system }}
          path: ${{ needs.meta.outputs.package }}_${{ matrix.system }}.gz
          archive: false

  publish-github:
    name: Publish binaries to GitHub
    needs:
      - meta
      - build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          ref: ${{ needs.version.outputs.tag }}
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
        with:
          name: tweag-tricorder
          authToken: "${{ secrets.CACHIX_TWEAG_TRICORDER_AUTH_TOKEN }}"
      - name: Extract from CHANGELOG
        run: |
          set -euo pipefail
          nix run .#get-changelog-section -- \
            "${{ needs.version.outputs.version }}" \
            ${{ needs.meta.outputs.package }}/CHANGELOG.md \
          | tee release-notes.md

          date="$(cat release-notes.md | head -1 | sed 's/^## \[[0-9.]*\] - //')"
          link_ref="$(echo "${{ needs.version.outputs.version }}" | tr --delete '.')---$date"}

          cat >> release-notes.md <<EOF

          ---

          See [the change log](./${{ needs.meta.outputs.package }}/CHANGELOG.md#$link_ref) for a full list of changes.
          EOF
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          pattern: ${{ needs.meta.outputs.package }}_*
          path: binaries
          merge-multiple: true
      - name: Publish to GitHub
        run: |
          gh release create \
            '${{ needs.meta.outputs.tag }}' \
            --draft \
            --title '${{ needs.meta.outputs.package }} ${{ needs.meta.outputs.version }}' \
            --notes-file release-notes.md \
            --verify-tag \
            binaries/*.gz
        env:
          GH_TOKEN: ${{ github.token }}
